
//Words will be tested
			newVocabulary = new Array(
			 "abbess",
			 "abbot",
			 "abed",
			 "abet",
			 "abhorrence",
			 "awaken",
			 "awry", 
			 "aye",
			 "azalea",
			 "azure", 
			 "Baconian", 
			 "bacterium", 
			 "badger", 
			 "baffle", 
			 "bailiff",
			 "bursar", 
			 "bustle", 
			 "butt", 
			 "butte", 
			 "buttress",
			 "cabal", 
			 "cabalism", 
			 "cabinet",
			 "cacophony", 
			 "cadaverous",
			 "cycloid", 
			 "cygnet", 
			 "cynical", 
			 "cynicism", 
			 "cynosure", 
			 "daring", 
			 "darkling",  
			 "Darwinism", 
			 "dastard", 
			 "datum",
			 "duteous", 
			 "dutiable",  
			 "dutiful", 
			 "dwindle",
			 "dyne", 
			 "earnest", 
			 "earthenware", 
			 "eatable", 
			 "ebullient", 
			 "eccentric",
			 "extremity", 
			 "extricate", 
			 "extrude",
			 "exuberance",  
			 "exuberant",  
			 "fabricate", 
			 "fabulous", 
			 "facet", 
			 "facetious", 
			 "facial",
			 "gauge", 
			 "gaiety", 
			 "gaily", 
			 "gait", 
			 "gallant", 
			 "habitable",  
			 "habitant", 
			 "habitual", 
			 "habitude", 
			 "hackney", 
			 "ichthyic", 
			 "ichthyology", 
			 "ichthyosaurs", 
			 "icily", 
			 "iciness", 
			 "jargon", 
			 "jaundice", 
			 "jeopardize", 
			 "Jingo", 
			 "jocose",
			 "keepsake", 
			 "kerchief", 
			 "kernel", 
			 "kiln", 
			 "kiloliter", 
			 "laborious", 
			 "labyrinth", 
			 "lacerate",
			 "lackadaisical", 
			 "lactation", 
			 "macadamize", 
			 "machinery", 
			 "machinist", 
			 "macrocosm",
			 "madden",
			 "nameless", 
			 "naphtha", 
			 "Narcissus", 
			 "narrate",  
			 "narration", 
			 "oaken", 
			 "oakum", 
			 "obdurate", 
			 "obelisk", 
			 "obese", 
			 "pacify", 
			 "packet", 
			 "pact", 
			 "pagan", 
			 "pageant", 
			 "quackery", 
			 "quadrate", 
			 "quadruple", 
			 "qualification", 
			 "qualify", 
			 "rabid", 
			 "racy", 
			 "radiance", 
			 "radiate", 
			 "radical", 
			 "sacrifice", 
			 "sacrificial", 
			 "sacrilege",  
			 "sacrilegious", 
			 "safeguard", 
			 "tableau", 
			 "tacit", 
			 "taciturn", 
			 "tack", 
			 "tact",  
			 "ubiquitous", 
			 "ulterior", 
			 "ultimate",  
			 "ultimatum", 
			 "ultramundane", 
			 "vacate", 
			 "vaccinate", 
			 "vacillate", 
			 "vacuous", 
			 "vacuum", 
			 "waif", 
			 "waistcoat", 
			 "waive", 
			 "wampum", 
			 "wane", 
			 "yearling", 
			 "zealot", 
			 "zeitgeist", 
			 "zenith", 
			 "zephyr", 
			 "zodiac" 
			);


//explanation for the above words, one explaination per word
			vocabularyExplanations = new Array(
			"The lady superior of a nunnery",
			"The superior of a community of monks",
			"on a bed",
			"To aid, promote, or encourage the commission of (an offense)", 
			"The act of detesting extremely",
			"To arouse, as emotion, interest, or the like",
			"Out of the proper form, direction, or position", 
			"An expression of assent",
			"A flowering shrub",
			"The color of the sky",
			"Of or pertaining to Lord Bacon or his system of philosophy",
			"A microbe",
			"To pester",
			"To foil or frustrate", 
			"An officer of court having custody of prisoners under arraignment", 
			"A treasurer", 
			"To hurry", 
			"To strike with or as with the head, or horns", 
			"A conspicuous hill, low mountain, or natural turret, generally isolated", 
			"Any support or prop", 
			"A number of persons secretly united for effecting by intrigue some private purpose", 
			"Superstitious devotion to one's religion",
			"The body of men constituting the official advisors of the executive head of a nation", 
			"A disagreeable, harsh, or discordant sound or combination of sounds or tones",
			"Resembling a corpse",
			"Like a circle", 
			"A young swan", 
			"Exhibiting moral skepticism", 
			"Contempt for the opinions of others and of what others value", 
			"That to which general interest or attention is directed", 
			"Brave", 
			"Blindly",
			"The doctrine that natural selection has been the prime cause of evolution of higher forms", 
			"A base coward", 
			"A premise, starting-point, or given fact",
			"Showing submission to natural superiors", 
			"Subject to a duty, especially a customs duty", 
			"Obedient", 
			"To diminish or become less", 
			"The force which, applied to a mass of one gram for 1 second, would give it a velocity of 1 cm/s",   
			"Ardent in spirit and speech", 
			"Anything made of clay and baked in a kiln or dried in the sun", 
			"Edible",
			"Showing enthusiasm or exhilaration of feeling",
			"Peculiar",
			"The utmost point, side, or border, or that farthest removed from a mean position",
			"Disentangle", 
			"To drive out or away",
			"Rich supply", 
			"Marked by great plentifulness", 
			"To invent fancifully or falsely", 
			"Incredible", 
			"One of the small triangular plane surfaces of a diamond or other gem", 
			"Amusing",
			"Pertaining to the face",
			"An instrument for measuring", 
			"Festivity", 
			"Merrily", 
			"Carriage of the body in going", 
			"Possessing a brave or chivalrous spirit", 
			"Fit to be dwelt in", 
			"Dweller", 
			"According to usual practice", 
			"Customary relation or association", 
			"To make stale or trite by repetition",
			"Fish-like", 
			"The branch of zoology that treats of fishes", 
			"A fossil reptile", 
			"Frigidly", 
			"The state of being icy", 
			"Confused, unintelligible speech or highly technical speech", 
			"A morbid condition, due to obstructed excretion of bile or characterized by yellowing of the skin",
			"To imperil",
			"One of a party in Great Britain in favor of spirited and demonstrative foreign policy", 
			"Done or made in jest", 
			"Anything kept or given to be kept for the sake of the giver", 
			"A square of linen, silk, or other material, used as a covering for the head or neck", 
			"A grain or seed", 
			"An oven or furnace for baking, burning, or drying industrial products", 
			"One thousand liters", 
			"Toilsome", 
			"A maze", 
			"To tear rudely or raggedly", 
			"Listless", 
			"The secretion of milk",
			"To cover or pave, as a path or roadway, with small broken stone",
			"The parts of a machine or engine, taken collectively", 
			"One who makes or repairs machines, or uses metal-working tools", 
			"The whole of any sphere or department of nature or knowledge to which man is related",
			"To inflame with passion",
			"Having no fame or reputation", 
			"A light, colorless, volatile, inflammable oil used as a solvent, as in manufacture of paints", 
			"The son of the Athenian river-god Cephisus, fabled to have fallen in love with his reflection",
			"To tell a story", 
			"The act of recounting the particulars of an event in the order of time or occurrence", 
			"Made of or from oak", 
			"Hemp-fiber obtained by untwisting and picking out loosely the yarns of old hemp rope", 
			"Impassive to feelings of humanity or pity", 
			"A square shaft with pyramidal top, usually monumental or commemorative", 
			"Exceedingly fat", 
			"To bring into a peaceful state", 
			"A bundle, as of letters", 
			"A covenant", 
			"A worshiper of false gods", 
			"A dramatic representation, especially a spectacular one", 
			"Charlatanry", 
			"To divide into quarters", 
			"To multiply by four", 
			"A requisite for an employment, position, right, or privilege",
			"To endow or furnish with requisite ability, character, knowledge, skill, or possessions", 
			"Affected with rabies or hydrophobia", 
			"Exciting or exhilarating to the mind", 
			"Brilliant or sparkling luster", 
			"To extend in all directions, as from a source or focus", 
			"One who holds extreme views or advocates extreme measures",
			"To make an offering of to deity, especially by presenting on an altar", 
			"Offering or offered as an atonement for sin", 
			"The act of violating or profaning anything sacred", 
			"Impious", 
			"To protect", 
			"An arrangement of inanimate figures representing a scene from real life", 
			"Understood", 
			"Disinclined to conversation", 
			"A small sharp-pointed nail", 
			"Fine or ready mental discernment shown in saying or doing the proper thing", 
			"Being present everywhere", 
			"Not so pertinent as something else to the matter spoken of", 
			"Beyond which there is nothing else", 
			"A final statement or proposal, as concerning terms or conditions", 
			"Pertaining to supernatural things or to another life", 
			"To leave", 
			"To inoculate with vaccine virus or virus of cowpox", 
			"To waver", 
			"Empty", 
			"A space entirely devoid of matter",
			"A homeless, neglected wanderer", 
			"A vest", 
			"To relinquish, especially temporarily, as a right or claim", 
			"Beads strung on threads, formerly used among the American Indians as currency", 
			"To diminish in size and brilliancy", 
			"A young animal past its first year and not yet two years old", 
			"One who espouses a cause or pursues an object in an immoderately partisan manner", 
			"The intellectual and moral tendencies that characterize any age or epoch", 
			"The culminating-point of prosperity, influence, or greatness", 
			"Any soft, gentle wind", 
			"An imaginary belt encircling the heavens within which are the larger planets"
			); 

