
//Words will be tested
			newVocabulary = new Array(
			 "abbess",
			 "abbot",
			 "abed",
			 "abet",
			 "abhorrence",
			 "awaken",
			 "awry", 
			 "aye",
			 "azalea",
			 "azure", 
			 "Baconian", 
			 "bacterium", 
			 "badger", 
			 "baffle", 
			 "bailiff",
			 "bursar", 
			 "bustle", 
			 "butt", 
			 "butte", 
			 "buttress",
			 "cabal", 
			 "cabalism", 
			 "cabinet",
			 "cacophony", 
			 "cadaverous",
			 "cycloid", 
			 "cygnet", 
			 "cynical", 
			 "cynicism", 
			 "cynosure", 
			 "daring", 
			 "darkling",  
			 "Darwinism", 
			 "dastard", 
			 "datum",
			 "duteous", 
			 "dutiable",  
			 "dutiful", 
			 "dwindle",
			 "dyne", 
			 "earnest", 
			 "earthenware", 
			 "eatable", 
			 "ebullient", 
			 "eccentric",
			 "extremity", 
			 "extricate", 
			 "extrude",
			 "exuberance",  
			 "exuberant",  
			 "fabricate", 
			 "fabulous", 
			 "facet", 
			 "facetious", 
			 "facial",
			 "facile", 
			 "facilitate", 
			 "facility", 
			 "facsimile", 
			 "faction", 
			 "gauge", 
			 "gaiety", 
			 "gaily", 
			 "gait", 
			 "gallant", 
			 "galore",
			 "galvanic",
			 "galvanism",
			 "galvanize",
			 "gamble",
			 "habitable",  
			 "habitant", 
			 "habitual", 
			 "habitude", 
			 "hackney", 
			 "haggard", 
			 "halcyon",
			 "hale", 
			 "handwriting",
			 "hanger-on", 
			 "ichthyic", 
			 "ichthyology", 
			 "ichthyosaurs", 
			 "icily", 
			 "iciness", 
			 "isolate", 
			 "isothermal", 
			 "itinerant",
			 "itinerary", 
			 "itinerate", 
			 "jargon", 
			 "jaundice", 
			 "jeopardize", 
			 "Jingo", 
			 "jocose",
			 "juror", 
			 "joust",
			 "justification", 
			 "juvenile", 
			 "juxtapose",  
			 "keepsake", 
			 "kerchief", 
			 "kernel", 
			 "kiln", 
			 "kiloliter", 
			 "knavery",
			 "knead", 
			 "knickknack",
			 "knight",
			 "knighthood",
			 "laborious", 
			 "labyrinth", 
			 "lacerate",
			 "lackadaisical", 
			 "lactation", 
			 "luxuriant", 
			 "luxuriate", 
			 "lying", 
			 "lyre", 
			 "lyric", 
			 "macadamize", 
			 "machinery", 
			 "machinist", 
			 "macrocosm",
			 "madden",
			 "myriad", 
			 "mystic", 
			 "mystification", 
			 "myth",  
			 "mythology", 
			 "nameless", 
			 "naphtha", 
			 "Narcissus", 
			 "narrate",  
			 "narration",
			 "nunnery", 
			 "nuptial", 
			 "nurture", 
			 "nutriment", 
			 "nutritive",  
			 "oaken", 
			 "oakum", 
			 "obdurate", 
			 "obelisk", 
			 "obese", 
			 "overstride", 
			 "overthrow",
			 "overtone", 
			 "overture",  
			 "overweight",
			 "pacify", 
			 "packet", 
			 "pact", 
			 "pagan", 
			 "pageant",
			 "putrescent",  
			 "pyre", 
			 "pyromania", 
			 "pyrotechnic",
			 "pyx",   
			 "quackery", 
			 "quadrate", 
			 "quadruple", 
			 "qualification", 
			 "qualify", 
			 "quietus",  
			 "quintessence", 
			 "quintet", 
			 "quite", 
			 "quixotic", 
			 "rabid", 
			 "racy", 
			 "radiance", 
			 "radiate", 
			 "radical", 
			 "sacrifice", 
			 "sacrificial", 
			 "sacrilege",  
			 "sacrilegious", 
			 "safeguard", 
			 "tableau", 
			 "tacit", 
			 "taciturn", 
			 "tack", 
			 "tact",  
			 "ubiquitous", 
			 "ulterior", 
			 "ultimate",  
			 "ultimatum", 
			 "ultramundane", 
			 "vacate", 
			 "vaccinate", 
			 "vacillate", 
			 "vacuous", 
			 "vacuum", 
			 "waif", 
			 "waistcoat", 
			 "waive", 
			 "wampum", 
			 "wane", 
			 "yearling", 
			 "zealot", 
			 "zeitgeist", 
			 "zenith", 
			 "zephyr", 
			 "zodiac" 
			);


//explanation for the above words, one explaination per word
			vocabularyExplanations = new Array(
			"The lady superior of a nunnery",
			"The superior of a community of monks",
			"on a bed",
			"To aid, promote, or encourage the commission of (an offense)", 
			"The act of detesting extremely",
			"To arouse, as emotion, interest, or the like",
			"Out of the proper form, direction, or position", 
			"An expression of assent",
			"A flowering shrub",
			"The color of the sky",
			"Of or pertaining to Lord Bacon or his system of philosophy",
			"A microbe",
			"To pester",
			"To foil or frustrate", 
			"An officer of court having custody of prisoners under arraignment", 
			"A treasurer", 
			"To hurry", 
			"To strike with or as with the head, or horns", 
			"A conspicuous hill, low mountain, or natural turret, generally isolated", 
			"Any support or prop", 
			"A number of persons secretly united for effecting by intrigue some private purpose", 
			"Superstitious devotion to one's religion",
			"The body of men constituting the official advisors of the executive head of a nation", 
			"A disagreeable, harsh, or discordant sound or combination of sounds or tones",
			"Resembling a corpse",
			"Like a circle", 
			"A young swan", 
			"Exhibiting moral skepticism", 
			"Contempt for the opinions of others and of what others value", 
			"That to which general interest or attention is directed", 
			"Brave", 
			"Blindly",
			"The doctrine that natural selection has been the prime cause of evolution of higher forms", 
			"A base coward", 
			"A premise, starting-point, or given fact",
			"Showing submission to natural superiors", 
			"Subject to a duty, especially a customs duty", 
			"Obedient", 
			"To diminish or become less", 
			"The force applied to a mass of one gram for 1 second, a velocity of 1 cm/s",   
			"Ardent in spirit and speech", 
			"Anything made of clay and baked in a kiln or dried in the sun", 
			"Edible",
			"Showing enthusiasm or exhilaration of feeling",
			"Peculiar",
			"The utmost point, side, or border, or that farthest removed from a mean position",
			"Disentangle", 
			"To drive out or away",
			"Rich supply", 
			"Marked by great plentifulness", 
			"To invent fancifully or falsely", 
			"Incredible", 
			"One of the small triangular plane surfaces of a diamond or other gem", 
			"Amusing",
			"Pertaining to the face",
			"An instrument for measuring", 
			"Not difficult to do", 
			"To make more easy",
			"Ease", 
 			"An exact copy or reproduction", 
 			"A number of persons combined for a common purpose", 
			"Festivity", 
			"Merrily", 
			"Carriage of the body in going", 
			"Possessing a brave or chivalrous spirit",
			"Abundant",
			"Pertaining or relating to electricity produced by chemical action", 
			"Current electricity, especially that arising from chemical action",
			"To imbue with life or animation",
			"To risk money or other possession on an event an event, chance, or contingency",  
			"Fit to be dwelt in", 
			"Dweller", 
			"According to usual practice", 
			"Customary relation or association", 
			"To make stale or trite by repetition",
			"Worn and gaunt in appearance", 
			"Calm", 
			"Of sound and vigorous health", 
			"Penmanship", 
			"A parasite", 
			"Fish-like", 
			"The branch of zoology that treats of fishes", 
			"A fossil reptile", 
			"Frigidly", 
			"The state of being icy", 
			"To separate from others of its kind", 
			"Having or marking equality of temperature",
			"Wandering", 
			"A detailed account or diary of a journey",
			"To wander from place to place",
			"Confused, unintelligible speech or highly technical speech", 
			"A morbid condition due to obstructed excretion of bile or characterized by yellowing of the skin",
			"To imperil",
			"One of a party in Great Britain in favor of spirited and demonstrative foreign policy", 
			"Done or made in jest", 
			"One who serves on a jury or is sworn in for jury duty in a court of justice", 
			"To engage in a tilt with lances on horseback", 
			"Vindication", 
			"Characteristic of youth",
			"To place close together", 
			"Anything kept or given to be kept for the sake of the giver", 
			"A square of linen, silk, or other material, used as a covering for the head or neck", 
			"A grain or seed", 
			"An oven or furnace for baking, burning, or drying industrial products", 
			"One thousand liters", 
			"Deceitfulness in dealing", 
			"To mix and work into a homogeneous mass, especially with the hands", 
			"A small article, more for ornament that use",
			"One of the wandering knights in the middle ages went forth in search of adventure",
			"Chivalry", 
			"Toilsome", 
			"A maze", 
			"To tear rudely or raggedly", 
			"Listless", 
			"The secretion of milk",
			"Abundant or superabundant in growth", 
			"To live sumptuously", 
			"Untruthfulness", 
			"One of the most ancient of stringed instruments of the harp class", 
			"Fitted for expression in song", 
			"To cover or pave, as a path or roadway, with small broken stone",
			"The parts of a machine or engine, taken collectively", 
			"One who makes or repairs machines, or uses metal-working tools", 
			"The whole of any sphere or department of nature or knowledge to which man is related",
			"To inflame with passion",
			"A vast indefinite number", 
			"One who professes direct divine illumination, or relies upon meditation to acquire truth", 
			"The act of artfully perplexing", 
			"A fictitious narrative presented as historical, but without any basis of fact", 
			"The whole body of legends cherished by a race concerning gods and heroes",
			"Having no fame or reputation", 
			"A light, colorless, volatile, inflammable oil used as a solvent", 
			"The son of the Athenian river-god Cephisus who have fallen in love with his reflection",
			"To tell a story", 
			"The act of recounting the particulars of an event in the order of time or occurrence", 
			"A convent for nuns", 
			"Of or pertaining to marriage, especially to the marriage ceremony", 
			"The process of fostering or promoting growth", 
			"That which nourishes",
			"Having nutritious properties", 
			"Made of or from oak", 
			"Hemp-fiber obtained by untwisting and picking out loosely the yarns of old hemp rope", 
			"Impassive to feelings of humanity or pity", 
			"A square shaft with pyramidal top, usually monumental or commemorative", 
			"Exceedingly fat", 
			"To step beyond", 
			"To vanquish an established ruler or government", 
			"A harmonic", 
			"An instrumental prelude to an opera, oratorio, or ballet", 
			"Preponderance", 
			"To bring into a peaceful state", 
			"A bundle, as of letters", 
			"A covenant", 
			"A worshiper of false gods", 
			"A dramatic representation, especially a spectacular one", 
			"Undergoing decomposition of animal or vegetable matter accompanied by fetid odors",
			"A heap of combustibles arranged for burning a dead body", 
			"An insane propensity to set things on fire", 
			"Pertaining to fireworks or their manufacture", 
			"A vessel or casket, usually of precious metal, in which the host is preserved", 
			"Charlatanry", 
			"To divide into quarters", 
			"To multiply by four", 
			"A requisite for an employment, position, right, or privilege",
			"To endow or furnish with requisite ability, character, knowledge, skill, or possessions", 
			"A silencing, suppressing, or ending", 
			"The most essential part of anything", 
			"Musical composition arranged for five voices or instruments", 
			"Fully", 
			"Chivalrous or romantic to a ridiculous or extravagant degree", 
			"Affected with rabies or hydrophobia", 
			"Exciting or exhilarating to the mind", 
			"Brilliant or sparkling luster", 
			"To extend in all directions, as from a source or focus", 
			"One who holds extreme views or advocates extreme measures",
			"To make an offering of to deity, especially by presenting on an altar", 
			"Offering or offered as an atonement for sin", 
			"The act of violating or profaning anything sacred", 
			"Impious", 
			"To protect", 
			"An arrangement of inanimate figures representing a scene from real life", 
			"Understood", 
			"Disinclined to conversation", 
			"A small sharp-pointed nail", 
			"Fine or ready mental discernment shown in saying or doing the proper thing", 
			"Being present everywhere", 
			"Not so pertinent as something else to the matter spoken of", 
			"Beyond which there is nothing else", 
			"A final statement or proposal, as concerning terms or conditions", 
			"Pertaining to supernatural things or to another life", 
			"To leave", 
			"To inoculate with vaccine virus or virus of cowpox", 
			"To waver", 
			"Empty", 
			"A space entirely devoid of matter",
			"A homeless, neglected wanderer", 
			"A vest", 
			"To relinquish, especially temporarily, as a right or claim", 
			"Beads strung on threads, formerly used among the American Indians as currency", 
			"To diminish in size and brilliancy", 
			"A young animal past its first year and not yet two years old", 
			"One who espouses a cause or pursues an object in an immoderately partisan manner", 
			"The intellectual and moral tendencies that characterize any age or epoch", 
			"The culminating-point of prosperity, influence, or greatness", 
			"Any soft, gentle wind", 
			"An imaginary belt encircling the heavens within which are the larger planets"
			); 

//wordSurfix library
var wordSurfix = [
"able",
"acy",
"age", 
"al", 
"an", 
"ance", 
"ancy", 
"ant",
"ar",
"ary",
"ate", 
"ation", 
"ative",
"dom",
"ed", 
"en",
"ence",
"ent",
"er",
"est",
"ful", 
"ia",
"ial",
"ian",
"iatry", 
"ible", 
"ic", 
"icl", 
"ics",  
"ice",  
"ient",   
"itive", 
"ify", 
"ile", 
"ing",  
"ion", 
"ish",  
"ism",  
"ist",  
"ite", 
"ity", 
"ium",
"ive", 
"ize", 
"less", 
"ment", 
"-on", 
"or",  
"ory",  
"ous", 
"ship",
"tude",  
"ty",  
"ure", 
"ware", 
"y"  
];

/*use a word's first six letters to represent a word 
if more than one word has the same first six letters, number will be used, start from 1. 
*/

// a seven-letter word whose surfix is in the below library, likely labeled as the first six letter and a digit higher than 1 
var sevenSurfix =[
"ance", 
"ancy", 
"ant",
"ial",  
"ian", 
"iatry",
"er",
"ia",
"ial",
"ian",
"iatry",  
"icl", 
"ics",  
"ice", 
"ish",  
"ism",  
"ist",  
"ite",  
"ity", 
"or",  
"ory",  
"ty", 
];   

// a eight-letter word whose surfix is in the below library, likely labeled as the first six letter and a digit higher than 1 

var eightSurfix =[
"acy",
"age", 
"al", 
"ance", 
"ancy", 
"ant",
"ar",
"ary",
"ate", 
"ation", 
"ative",
"ed", 
"en",
"ence",
"ent",
"er",
"est",
"ia",
"ial",
"ian",
"ic", 
"icl", 
"ics",  
"ice", 
"ify", 
"ile", 
"ing",  
"ion", 
"ish",  
"ism",  
"ist",  
"ite", 
"ity", 
"ium",
"ive", 
"ize", 
"or",  
"ory",  
"ous",
"ty",
"y"  
]; 

// a nine-letter word whose surfix is in the below library, likely labeled as the first six letter and a digit higher than 1 
var nineSurfix =[
"acy",
"age", 
"al", 
"an", 
"ance", 
"ancy", 
"ant",
"ar",
"ary",
"ate", 
"ation", 
"ative",
"dom",
"ed", 
"en",
"ence",
"ent",
"er",
"est",
"ful", 
"ia",
"ial",
"ian",
"iatry", 
"ible", 
"ic", 
"icl", 
"ics",  
"ice",  
"ient",
"ify", 
"ile", 
"ing",  
"ion", 
"ish",  
"ism",  
"ist",  
"ite", 
"ity", 
"ium",
"ive", 
"ize", 
"-on",
"or",  
"ory",  
"ous",
"tude",  
"ty",  
"ure",  
"y"  
]   

//object
var wordExclude =[
  "eccentric",
  "extricate",
  "exuberance",
  "habitual",
  "facsimile",
  "fabulous",
  "facilitate"
  ]

  var wordInclude =[
 "cynosure",
 "habitude"
  ]